### ISSUE TITLE
terminar completar examples.conllu

### ISSUE THREAD

**Issue by arademaker** [LR-POR/ud-matrix#4]
completar arquivo examples.conllu com sentenças de https://github.com/LR-POR/PorGram/issues/19#issuecomment-902317884

**Comment by wellington36** [comment]
Com 7a1e723017b9354bc4ec5d898b714a7a19436865 adicionei linhas 7 e 8 referentes a tabela https://github.com/LR-POR/PorGram/issues/19#issuecomment-902317884.

**Comment by wellington36** [comment]
@arademake, Com 136f8c6ff684da3ae9dd509c6c3348ebb91ef3ba adicionei linhas 1, 10, 11 e 12 referentes a tabela https://github.com/LR-POR/PorGram/issues/19#issuecomment-902317884.

**Comment by wellington36** [comment]
A tabela em questão foi criada em https://github.com/LR-POR/ud-matrix/blob/master/examples.conllu, e terminada no commit 307d5a446318eef14976b5555fbe5dedaa7dc02e correções na mesma podem ser feitos pelo issue #3.
